
package fr.univartois.ili.sadoc.client.webservice.tools;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SadocServices", targetNamespace = "http://sadoc.com/ac/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SadocServices {


    /**
     * 
     * @param createOwnerRequest
     * @return
     *     returns com.sadoc.ac.schemas.CreateOwnerResponse
     */
    @WebMethod
    @WebResult(name = "createOwnerResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "createOwnerResponse")
    public CreateOwnerResponse createOwner(
        @WebParam(name = "createOwnerRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "createOwnerRequest")
        CreateOwnerRequest createOwnerRequest);

    /**
     * 
     * @param signDocumentRequest
     * @return
     *     returns com.sadoc.ac.schemas.SignDocumentResponse
     */
    @WebMethod
    @WebResult(name = "signDocumentResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "signDocumentResponse")
    public SignDocumentResponse signDocument(
        @WebParam(name = "signDocumentRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "signDocumentRequest")
        SignDocumentRequest signDocumentRequest);

    /**
     * 
     * @param getOwnerRequest
     */
    @WebMethod
    @Oneway
    public void getOwner(
        @WebParam(name = "getOwnerRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "getOwnerRequest")
        GetOwnerRequest getOwnerRequest);

    /**
     * 
     * @param getDocumentInformationsRequest
     * @return
     *     returns com.sadoc.ac.schemas.GetDocumentInformationsResponse
     */
    @WebMethod
    @WebResult(name = "getDocumentInformationsResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "getDocumentInformationsResponse")
    public GetDocumentInformationsResponse getDocumentInformations(
        @WebParam(name = "getDocumentInformationsRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "getDocumentInformationsRequest")
        GetDocumentInformationsRequest getDocumentInformationsRequest);

   
    /**
     * 
     * @param verifyDocumentRequest
     * @return
     *     returns com.sadoc.ac.schemas.VerifyDocumentResponse
     */
    @WebMethod
    @WebResult(name = "verifyDocumentResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "verifyDocumentResponse")
    public VerifyDocumentResponse verifyDocument(
        @WebParam(name = "verifyDocumentRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "verifyDocumentRequest")
        VerifyDocumentRequest verifyDocumentRequest);

    /**
     * 
     * @param getDocumentRequest
     * @return
     *     returns com.sadoc.ac.schemas.GetDocumentResponse
     */
    @WebMethod
    @WebResult(name = "getDocumentResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "getDocumentResponse")
    public GetDocumentResponse getDocument(
        @WebParam(name = "getDocumentRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "getDocumentRequest")
        GetDocumentRequest getDocumentRequest);

   
    /**
     * 
     * @param createCertificateRequest
     * @return
     *     returns com.sadoc.ac.schemas.CreateCertificateResponse
     */
    @WebMethod
    @WebResult(name = "createCertificateResponse", targetNamespace = "http://sadoc.com/ac/schemas", partName = "createCertificateResponse")
    public CreateCertificateResponse createCertificate(
        @WebParam(name = "createCertificateRequest", targetNamespace = "http://sadoc.com/ac/schemas", partName = "createCertificateRequest")
        CreateCertificateRequest createCertificateRequest);

}
