DROP DATABASE IF EXISTS SADOCCO ;
CREATE DATABASE SADOCCO ;

USE SADOCCO ;

DROP TABLE IF EXISTS REFERENTIEL ;
CREATE TABLE IF NOT EXISTS REFERENTIEL (
  ID bigint(20) AUTO_INCREMENT NOT NULL, 
  CODEREFERENTIEL VARCHAR(255), 
  DESCRIPTION VARCHAR(255), 
  NAME VARCHAR(255), 
  SEUIL bigint(20), 
  URL VARCHAR(255),
  PRIMARY KEY (ID)
) ;

DROP TABLE IF EXISTS DOMAINE ;
CREATE TABLE IF NOT EXISTS DOMAINE (
  ID bigint(20) AUTO_INCREMENT NOT NULL, 
  CODEDOMAINE VARCHAR(255), 
  DESCRIPTION VARCHAR(255), 
  REFERENTIEL_ID  bigint(20), 
  PRIMARY KEY (ID),
  FOREIGN KEY (REFERENTIEL_ID) REFERENCES REFERENTIEL(ID)
) ;

DROP TABLE IF EXISTS COMPETENCE ;
CREATE TABLE IF NOT EXISTS COMPETENCE (
  ID bigint(20) AUTO_INCREMENT NOT NULL, 
  CODECOMPETENCE VARCHAR(255), 
  DESCRIPTION VARCHAR(255), 
  DOMAINE_ID  bigint(20), 
  PRIMARY KEY (ID),
  FOREIGN KEY (DOMAINE_ID) REFERENCES DOMAINE(ID)
) ;

DROP TABLE IF EXISTS ITEM ;
CREATE TABLE IF NOT EXISTS ITEM (
  ID bigint(20) AUTO_INCREMENT NOT NULL, 
  CODEITEM VARCHAR(255), 
  DESCRIPTION VARCHAR(255), 
  EMPREINTE bigint(20),
  POIDS bigint(20),
  TYPE VARCHAR(255),
  COMPETENCE_ID bigint(20), 
  PRIMARY KEY (ID),
  FOREIGN KEY (COMPETENCE_ID) REFERENCES COMPETENCE(ID)
) ;
